version: "3"
services:
    mysql:  
       image: mysql:latest
       container_name: mysql_container
       volumes:
            - mysql_volume:/var/lib/mysql
       networks:
            - my_network     
       environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=vital_details
    vitals:
       image: davita-vital-details:1.0
       container_name: vital-details
       networks:
            - my_network
       environment:
            - RDS_HOSTNAME=mysql_container
       depends_on:
            - mysql
       ports:
            - "8080:8080"
        
volumes:
    mysql_volume:

 

networks:
    my_network:
